"""initial migration

Revision ID: 5dd377e860f3
Revises: 
Create Date: 2025-01-10 00:10:22.321285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd377e860f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('complete_date', sa.DateTime(), nullable=True),
    sa.Column('bm_scrape_count', sa.Integer(), nullable=True),
    sa.Column('tw_scrape_count', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('execution_context', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('booz',
    sa.Column('booz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booz_name', sa.String(length=200), nullable=False),
    sa.Column('source_site', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('scrape_method', sa.String(length=50), nullable=False),
    sa.Column('product_identifier', sa.String(length=50), nullable=True),
    sa.Column('watchlist_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('watchlist_add_date', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.run_id'], ),
    sa.PrimaryKeyConstraint('booz_id')
    )
    op.create_table('booz_scraped',
    sa.Column('booz_scraped_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booz_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('scrape_date', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booz_id'], ['booz.booz_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.run_id'], ),
    sa.PrimaryKeyConstraint('booz_scraped_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booz_scraped')
    op.drop_table('booz')
    op.drop_table('run')
    # ### end Alembic commands ###
