"""force update

Revision ID: 633741d5f30f
Revises: 9b8128163ebf
Create Date: 2025-01-10 00:36:50.088074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '633741d5f30f'
down_revision: Union[str, None] = '9b8128163ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booz', 'scrape_method',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booz', 'scrape_method',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
