"""Use SQLAlchemy's server_default for datetime now fields

Revision ID: fe80c8e76e50
Revises: 120b614cab4a
Create Date: 2025-01-10 00:23:52.416407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe80c8e76e50'
down_revision: Union[str, None] = '120b614cab4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
